[project]
name = "devstandup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "taizeem0@gmail.com", email = "taizeem0@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "celery>=5.6.3",
    "django>=6.1.2",
    "djangorestframework>=3.18.3",
    "psycopg2-binary>=2.9.13",
    "python-dotenv>=1.2.4",
    "redis<5.0.0",
    "requests>=2.34.2",
]

[project.scripts]
devstandup = "devstandup:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
