# Generated by Django 6.1.2 on 2026-10-07 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandupDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest_date', models.DateField(help_text='The workday date this digest represents.')),
                ('compiled_at', models.DateTimeField(blank=True, null=True)),
                ('is_compiled', models.BooleanField(default=False)),
                ('missing_members_snapshot', models.JSONField(blank=True, default=list, help_text='List of member names flagged as missing at compiled deadline.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digests', to='teams.team')),
            ],
            options={
                'ordering': ['-digest_date'],
            },
        ),
        migrations.CreateModel(
            name='StandupEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standup_date', models.DateField(help_text='Target workday date according to team local timezone.')),
                ('yesterday', models.TextField(help_text='What I did since previous work day.')),
                ('today', models.TextField(help_text='What I am doing today.')),
                ('blockers', models.TextField(blank=True, default='', help_text="Blockers or 'None'.")),
                ('is_late', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('digest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='standups.standupdigest')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standups', to='teams.teammember')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standup_entries', to='teams.team')),
            ],
            options={
                'ordering': ['-standup_date', '-submitted_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='standupdigest',
            constraint=models.UniqueConstraint(fields=('team', 'digest_date'), name='unique_team_digest_date'),
        ),
        migrations.AddConstraint(
            model_name='standupentry',
            constraint=models.UniqueConstraint(fields=('member', 'standup_date'), name='unique_member_standup_per_date'),
        ),
    ]
