# Generated by Django 6.1.2 on 2026-10-07 05:12

import apps.teams.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('timezone', models.CharField(default='UTC', help_text="Standard IANA timezone name (e.g. 'America/New_York', 'Asia/Kolkata').", max_length=64, validators=[apps.teams.models.validate_timezone])),
                ('standup_time', models.TimeField(default=datetime.time(10, 0), help_text="Daily compilation deadline in the team's local timezone.")),
                ('webhook_url', models.URLField(max_length=500)),
                ('webhook_format', models.CharField(choices=[('SLACK', 'Slack Incoming Webhook'), ('DISCORD', 'Discord Webhook'), ('GENERIC', 'Generic Readable Markdown')], default='SLACK', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('external_mention_id', models.CharField(blank=True, help_text='Optional Slack/Discord user ID (e.g., U12345 or <@!12345>) for tagging in digests.', max_length=64)),
                ('is_active', models.BooleanField(default=True, help_text='If inactive, the member is excluded from standup compilation & missing member checks.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
                'constraints': [models.UniqueConstraint(fields=('team', 'user'), name='unique_team_user_membership')],
            },
        ),
    ]
